sudo: false
language: node_js
node_js:
  - "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn
  - yarn run lint
  - yarn run test:ci
  - yarn run build
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
